### ISSUE TITLE
Docker version is not working

### ISSUE THREAD

**Issue by billaram** [bzon/prometheus-msteams#20]
This is the error I am getting 

```
component=dispatcher msg="Notify for alerts failed" num_alerts=1 err="cancelling notify retry for \"webhook\" due to unrecoverable error: unexpected status code 404 from http://teamreceiver:2000/alertmanager"
```

**Comment by billaram** [comment]
Hi, The Issue has been resolved, there is an additional environment variable `TEAMS_REQUEST_URI` which is not specified in the docs. It would be better if you add sample docker-compose config as well. BTW I m using `dockprom` compose as base for my prometheus server.

`docker-compose.yml`

```
teamreceiver:
    image: docker.io/bzon/prometheus-msteams:1.0.0-rc.52
    container_name: teamreceiver
    expose:
      - 2000
    environment:
      - TEAMS_INCOMING_WEBHOOK_URL=xxxx
      - PROMTEAMS_DEBUG=true
      - TEAMS_REQUEST_URI=alertmanager
    depends_on:
      - alertmanager
```
`alert.config.yml`

```
route:
    receiver: 'prometheus-msteams'
receivers:
- name: 'prometheus-msteams'
      webhook_configs: # https://prometheus.io/docs/alerting/configuration/#webhook_config 
          - send_resolved: true
            url: 'http://teamreceiver:2000/alertmanager' # the prometheus-msteams proxy
```
