### ISSUE TITLE
Template Question

### ISSUE THREAD

**Issue by FewMagner** [bzon/prometheus-msteams#23]
Hey,

Can you tell me how to edit the template that is sent to MS Teams for example adding an external link - Is there a JSON template I can edit to include this?

I compared it to the Prom2Teams project where I was able to find the template, but I was not able to find it in this one. Can you point me in the right direction please.

Kind regards,
Laura

**Comment by bzon** [comment]
@FewMagner Currently, the "template" (the card format) is hard coded. See [here](https://github.com/bzon/prometheus-msteams/blob/c7803878356811a4b70d85e037384a9ecfb56847/alert/teams.go#L71-L104). I based this format from the [teams card spec](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/cards/cards-reference).

What do you mean by adding an external link? If you want to add a hyperlinked text to an alert card you can use labels. 

See the example alert rule below with **jenkins_link** label. You have to ensure to set **USE_MARKDOWN=true** to enable markdown rendering.

```yaml
- name: containers
  rules:
  - alert: jenkins_down
    expr: absent(container_memory_usage_bytes{name="jenkins"})
    for: 30s
    labels:
      severity: critical
      jenkins_link: [access jenkins here!](http://jenkins.example.com)
    annotations:
      summary: "Jenkins down"
      description: "Jenkins container is down for more than 30 seconds."
```
